using System;
using System.Diagnostics;

namespace Ouroboros.Document.Elements;

[Serializable]
[DebuggerDisplay("Text: { Text }")]
public class TextElement : ElementBase
{
    public override string Type()
    {
        return "Text";
    }

    /// <summary>
    /// True if this text element was generated by GPT.
    /// </summary>
    public bool IsGenerated { get; set; }

    public TextElement()
    {
        IsGenerated = false;
    }

    public TextElement(string text) : this()
    {
        Text = text;
    }
}