using System;
using System.Diagnostics;

namespace Ouroboros.Document.Elements;

[Serializable]
[DebuggerDisplay("Text: { Content }")]
internal class TextElement : ElementBase
{
    /// <summary>
    /// True if this text element was generated by GPT.
    /// </summary>
    public bool IsGenerated { get; set; }

    public TextElement()
    {
        IsGenerated = false;
    }

    public TextElement(string content) : this()
    {
        Content = content;
    }
}